name: Back-End CI

on:
  push:
    branches:
    - main
    - 'PIZ[0-9]*-*'
  pull_request:
    branches:
    - main
    - 'PIZ[0-9]*-*'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Create virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt
      - name: Set up database
        run: |
          source venv/bin/activate
          python manage.py db init
          python manage.py db migrate
          python manage.py db upgrade
      - name: Check Lint
        run: |
          source venv/bin/activate
          ruff check *.py
      - name: Run tests with coverage
        run: |
          source venv/bin/activate
          pytest --cov=app --cov-report=term --cov-fail-under=80 ./app/test
